### ISSUE TITLE
cant build kamailio container

### ISSUE THREAD

**Issue by rkalandyk** [jamhed/kazoo-docker#1]
perhaps problem is in nsq module

install -m 755 evbuffsock.h /usr/local/include/evbuffsock.h
cc -o command.o -c command.c -g -Wall -O2 -DDEBUG -fPIC
cc -o reader.o -c reader.c -g -Wall -O2 -DDEBUG -fPIC
reader.c: In function 'new_nsq_reader':
reader.c:112:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
     ev_timer_init(&rdr->lookupd_poll_timer, nsq_reader_lookupd_poll_cb, 0., 5.);
     ^
reader.c:112:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
reader.c:112:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
reader.c:112:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
cc -o nsqd_connection.o -c nsqd_connection.c -g -Wall -O2 -DDEBUG -fPIC
nsqd_connection.c: In function 'new_nsqd_connection':
nsqd_connection.c:117:9: warning: passing argument 4 of 'new_buffered_socket' makes integer from pointer without a cast
         nsqd_connection_connect_cb, nsqd_connection_close_cb,
         ^
In file included from nsq.h:9:0,
                 from nsqd_connection.c:1:
/usr/local/include/evbuffsock.h:69:24: note: expected 'size_t' but argument is of type 'void (_)(struct BufferedSocket *, void *)'
 struct BufferedSocket *new_buffered_socket(struct ev_loop *loop, const char *address, int port,
                        ^
nsqd_connection.c:117:37: warning: passing argument 5 of 'new_buffered_socket' makes integer from pointer without a cast
         nsqd_connection_connect_cb, nsqd_connection_close_cb,
                                     ^
In file included from nsq.h:9:0,
                 from nsqd_connection.c:1:
/usr/local/include/evbuffsock.h:69:24: note: expected 'size_t' but argument is of type 'void (_)(struct BufferedSocket _, void *)'
 struct BufferedSocket *new_buffered_socket(struct ev_loop *loop, const char *address, int port,
                        ^
nsqd_connection.c:118:9: warning: passing argument 6 of 'new_buffered_socket' makes integer from pointer without a cast
         NULL, NULL, nsqd_connection_error_cb,
         ^
In file included from nsq.h:9:0,
                 from nsqd_connection.c:1:
/usr/local/include/evbuffsock.h:69:24: note: expected 'size_t' but argument is of type 'void *'
 struct BufferedSocket *new_buffered_socket(struct ev_loop *loop, const char *address, int port,
                        ^
nsqd_connection.c:118:15: warning: passing argument 7 of 'new_buffered_socket' makes integer from pointer without a cast
         NULL, NULL, nsqd_connection_error_cb,
               ^
In file included from nsq.h:9:0,
                 from nsqd_connection.c:1:
/usr/local/include/evbuffsock.h:69:24: note: expected 'size_t' but argument is of type 'void *'
 struct BufferedSocket *new_buffered_socket(struct ev_loop *loop, const char *address, int port,
                        ^
nsqd_connection.c:119:9: warning: passing argument 9 of 'new_buffered_socket' from incompatible pointer type
         conn);
         ^
In file included from nsq.h:9:0,
                 from nsqd_connection.c:1:
/usr/local/include/evbuffsock.h:69:24: note: expected 'void (_)(struct BufferedSocket _, void *)' but argument is of type 'struct NSQDConnection *'
 struct BufferedSocket *new_buffered_socket(struct ev_loop *loop, const char *address, int port,
                        ^
nsqd_connection.c:116:16: error: too few arguments to function 'new_buffered_socket'
     conn->bs = new_buffered_socket(loop, address, port,
                ^
In file included from nsq.h:9:0,
                 from nsqd_connection.c:1:
/usr/local/include/evbuffsock.h:69:24: note: declared here
 struct BufferedSocket *new_buffered_socket(struct ev_loop *loop, const char *address, int port,
                        ^
make: *_\* [nsqd_connection.o] Error 1
Makefile:17: recipe for target 'nsqd_connection.o' failed
install -m 755 -d /usr/local/include
install -m 755 -d /usr/local/lib
install -m 755 libnsq.a /usr/local/lib/libnsq.a
install: cannot stat 'libnsq.a': No such file or directory
Makefile:32: recipe for target 'install' failed
make: **\* [install] Error 1
Makefile:107: config.mak: No such file or directory

Best Regards
Robert

**Comment by jamhed** [comment]
@rkalandyk thanks, I've fixed the version for libevsockbuff, builds now.
