### ISSUE TITLE
Freeswitch no audio

### ISSUE THREAD

**Issue by ghost** [jamhed/kazoo-docker#10]
This is probably my own lack of knowledge but i was wondering if i could get some pointers.
I set up everything form your script. 
I cant hear any audio in the calls both ways. 
i think its a free switch port thing. i might be wrong
i installed centos 7 and then converted from firewalld to ip-tables services
then i installed docker and ran your script. 

Could you tell me the manual way to set up the RTP ports.

**Comment by jamhed** [comment]
@onezerooneMod, could you describe your setup? E.g. what endpoints has no audio? I think normally it should work.

**Comment by ghost** [comment]
So i installed centos minimal on bare metal. Then i set a static ip. After that i disabled firewalld and installed iptables-services and enabled it and started it. Then  i installed docker-ce from docker official repository for centos. 
I downloaded your script. I dont have a resolvable domain name. Did set up a dns server on a non docker bare metal install and call wouldnt go through and kept giving a duplicate uuid error so i have been using just ips since then.  run.sh was assigning the public ip address for the crossbar api so i modified it and entered my static lan ip addresses :
if [ -z "$KAZOO_URI" ]
then
	EXT_IP=$(ifconfig eth0 | grep 'inet ' | cut -d 't' -f 2 | cut -d ' ' -f 2)
	echo "Guessing our Kazoo API uri: http://$EXT_IP/v2/"
	echo "Please specify it in KAZOO_URI env variable, e.g. http://your-server.domain, without /v2/ part, see nginx config"
	KAZOO_URI=$EXT_IP
fi
export KAZOO_URL=http://$EXT_IP/v2/



Other then that i exposed port 5984 on couchdb so i could access the database. 
I also modified RTP port for freeswitch to start from 16384 instead of the original. it was worth a try even though theoretically its not different than setting it to any number based on the way its fed as a system variable. 
I ran run.sh after that as it is

Audio not working after install . 
 Also i had to manually add kamailio to kazoo since for some reason it didnt work through the script . i found that it was added through allow_carrier instead of a allow_sbc in the script so i manually added it as a carrier. Is that ok? 

Also getting this in  monster-ui : 
warning api_resource.183 request with "X-Forwarded-For: 192.168.1.188" header, but peer (172.18.0.8) is not allowed as proxy


Also i see that "docker exec kamailio.kazoo kamcmd dispatcher.list | grep URI" gives two entries for freeswitch:
  DEST: {
                                        URI: sip:freeswitch.kazoo:11000
                                        FLAGS: AP
                                        PRIORITY: 1
                                        ATTRS: {
                                                BODY:
                                                DUID:
                                                MAXLOAD: 0
                                                WEIGHT: 0
                                                RWEIGHT: 0
                                                SOCKET:
                                        }
                                }
                                DEST: {
                                        URI: sip:freeswitch.kazoo:11000
                                        FLAGS: AX
                                        PRIORITY: 1
                                        ATTRS: {
                                                BODY:
                                                DUID:
                                                MAXLOAD: 0
                                                WEIGHT: 0
                                                RWEIGHT: 0
                                                SOCKET:
                                        }

here is my setup log.
starting: nginx.kazoo 6f5314373e7d5e0df78967ec1bb92b2600f6633ada932c4f20a3052bdb6ac967
Going to configure Kazoo, please wait for system to start up...
wait for kazoo.kazoo to start (you may check docker logs if impatient)
create master account: View updated!
created new account '9be286deb694e2c13483c61dd1e82693' in db 'account%2F9b%2Fe2%2F86deb694e2c13483c61dd1e82693'
created new account admin user '975393ef8b70cd35590c4e56a68caefa'
promoting account 9be286deb694e2c13483c61dd1e82693 to reseller status, updating sub accounts
updating master account id in system_config.accounts
ok
add freeswitch to kazoo: fs_nodes in kazoo@kazoo.kazoo was misconfigured(undefined), using []
adding freeswitch@freeswitch.kazoo to ecallmgr system config
ok
wait fot freeswitch to complete connect
add kamailio to kazoo with ip 172.18.0.5: updating trusted ACLs kamailio.kazoo(172.18.0.5/32) to allow traffic
issued reload ACLs to freeswitch@freeswitch.kazoo

here is my kazoo.kazoo container log
(kazoo@kazoo.kazoo)1> 13:39:08.619 |00000000000| notice ecallmgr_fs_nodes.653 successfully connected to freeswitch node freeswitch@freeswitch.kazoo
(kazoo@kazoo.kazoo)1> 13:39:08.619 |00000000000| notice ecallmgr_fs_nodes.653 successfully connected to freeswitch node freeswitch@freeswitch.kazoo
(kazoo@kazoo.kazoo)1> 13:39:12.502 |freeswitch@freeswitch.kazoo| notice ecallmgr_fs_node.686 fs sync complete




Everything else in the sanity check stuff is as expected and  working. 

Here are my iptables : 
-P INPUT ACCEPT
-P FORWARD ACCEPT
-P OUTPUT ACCEPT
-N DOCKER
-N DOCKER-ISOLATION
-A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
-A INPUT -p icmp -j ACCEPT
-A INPUT -i lo -j ACCEPT
-A INPUT -p tcp -m state --state NEW -m tcp --dport 22 -j ACCEPT
-A INPUT -j REJECT --reject-with icmp-host-prohibited
-A FORWARD -j DOCKER-ISOLATION
-A FORWARD -o br-4e36bdac3dfc -j DOCKER
-A FORWARD -o br-4e36bdac3dfc -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -i br-4e36bdac3dfc ! -o br-4e36bdac3dfc -j ACCEPT
-A FORWARD -i br-4e36bdac3dfc -o br-4e36bdac3dfc -j ACCEPT
-A FORWARD -o docker0 -j DOCKER
-A FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -i docker0 ! -o docker0 -j ACCEPT
-A FORWARD -i docker0 -o docker0 -j ACCEPT
-A FORWARD -j REJECT --reject-with icmp-host-prohibited
-A FORWARD -d 172.18.0.6/32 -p udp -m multiport --dports 16384:17383 -j ACCEPT
-A DOCKER -d 172.18.0.3/32 ! -i br-4e36bdac3dfc -o br-4e36bdac3dfc -p tcp -m tcp --dport 5984 -j ACCEPT
-A DOCKER -d 172.18.0.5/32 ! -i br-4e36bdac3dfc -o br-4e36bdac3dfc -p udp -m udp --dport 5060 -j ACCEPT
-A DOCKER -d 172.18.0.8/32 ! -i br-4e36bdac3dfc -o br-4e36bdac3dfc -p tcp -m tcp --dport 80 -j ACCEPT
-A DOCKER-ISOLATION -i docker0 -o br-4e36bdac3dfc -j DROP
-A DOCKER-ISOLATION -i br-4e36bdac3dfc -o docker0 -j DROP
-A DOCKER-ISOLATION -j RETURN



Thank you for your time 👍

**Comment by jamhed** [comment]
Yeah, it seems I need to re-check it, thanks for the report.

**Comment by jamhed** [comment]
@onezerooneMod, please update to latest: remove all containers from docker host, and run run.sh again, I've tweaked it a bit.

**Comment by jamhed** [comment]
See https://github.com/jamhed/kazoo-docker#networking as brief explanation.

**Comment by jamhed** [comment]
I suppose we can close this now.

**Comment by vijaymuddu** [comment]
Hi 
i am facing same issue on outboun and inbound calls, no audio but calls are getting placed
Using docker container with FS1.4 on centos 7, SIP connection is plugged on eth1 on host system, have added route.eth1 file in network-scripts with proper route config

SIP is getting registered in the container but no audio when called outbound

Can you please guide
