### ISSUE TITLE
create master account

### ISSUE THREAD

**Issue by block0xhash** [jamhed/kazoo-docker#11]
Hi

I am running run.sh  and I am getting this error:

wait for kazoo.kazoo to start (you may check docker logs if impatient)
create master account: failed to validate account properties(error): '{}'
failed

how can i revolve it

**Comment by jamhed** [comment]
Probably a broken build, try to update docker containers by cleaning your docker cache, e.g. `docker rmi`

**Comment by block0xhash** [comment]
Thanks working now
