### ISSUE TITLE
monster-ui problem

### ISSUE THREAD

**Issue by fholzhauser** [jamhed/kazoo-docker#13]
In the current monster-ui image there is a sort function missing from monster.util.js. Since more screens want to use it, this is probably a regression in monster-ui and it breaks quite a few things. If there is a fix for it in monster-ui then would it be possible to update the image ? Thanks in advance.

**Comment by ghost** [comment]
there has been a commit to monster-ui that has solved this issue. 
you can reproduce the changes by hand or make a new monster-ui container using the latest repo
https://github.com/2600hz/monster-ui/commit/729d8c23bc60564701d8d1edfcd9cbf4ce598963

**Comment by jamhed** [comment]
@fholzhauser, 2600hz/monster-ui is the latest monster-ui master.

**Comment by fholzhauser** [comment]
Probably this is not something you can help then. monster-ui needs fixing first.
I see what happened I think : https://github.com/2600hz/monster-ui/pull/82
The required changes for this renaming probably did not make it to the apps. Perhaps it would have been useful to keep the legacy function in monster.util until all apps are certainly updated (as it is normally done with such changes). Also user made apps (with no intention to update) might use it too.
Let's hope they'll fix it soon. Thanks for checking.

**Comment by UzairM** [comment]
My bad. Did not realize it's still not updated in apps. Most apps has app.js in their main folder. You can replace all instances of the depreciated feature with the new method in those. I am already going to be doing it for the VoIP app. If that's the one you want I can forward it to you once its working and you can overwrite it. I might as well make a commit request also. Will get to it around next week.

**Comment by jamhed** [comment]
I suppose we can close this now.
