### ISSUE TITLE
error,unknown_cache,ecallmgr_util_cache

### ISSUE THREAD

**Issue by Raixur** [jamhed/kazoo-docker#2]
![image](https://cloud.githubusercontent.com/assets/9009109/19193066/42bcbad4-8cb1-11e6-8b74-c91e57637dcc.png)
Kazoo sup not working properly. The only error I get before this "No container monster-ui-local.kazoo".

**Comment by nosovk** [comment]
То есть FreeSwitch Noda не подключается по какой то причине, хотя пользователь такой в ней есть (без пароля)

**Comment by jamhed** [comment]
Please rebuild the container, should work (I believe there were issues in master).

**Comment by Raixur** [comment]
Works fine on Debian(Jessie)/non root. Doesn't work on CentOS 7/root.
