### ISSUE TITLE
hosts.sh missing from production git repo.

### ISSUE THREAD

**Issue by krull** [jamhed/kazoo-docker#6]
@jamhed, On `README.md`, [host.sh](https://github.com/2600hz/docker/blob/master/hosts.sh) is missing from the production repo, although referenced in the the README file.

I am thoroughly enthused by the efforts done with 2600hz on kazoo + docker, and the quality of the project thus far! Also if I may, I can contrib the couchdb persistency listed in the TODO. Sending a PR your way once I am able.

EDIT: Also along with `host.sh`, [get-ip](https://github.com/2600hz/docker/blob/master/bin/get-ip)

Great docker work overall! A+

krull

**Comment by krull** [comment]
Update: seems that docker networking takes care of the hostnames of each container. Removing the host.sh part in the README.md file would clear the confusion.

Thanks!

**Comment by jamhed** [comment]
@krull, actually I think it's worth to add hosts to production too. Good catch anyway, thanks.

**Comment by krull** [comment]
@jamhed, following your `README.md`, -- from a QA standpoint -- yes, you do require the `host.sh` to generate your `/etc/hosts` file for you so that the host on a single docker server system can reach monster-ui.kazoo. _/mr_obvious_here heh_

However, I do have an SSL enabled `nginx:alpine` image here that does the real-world proxy_pass for monster-ui and api accesses from my external apps, and as such, the current state of your production build images passes on my tests so far. Moreover, I do not see why the host would need to access the kazoo containers other than what you provided with the `sup` wrapper script to do some kind of maintenance.

I am testing now how to get couchdb persistent on my install. I'm almost done. Will provide a PR soon. thanks!

krull

**Comment by jamhed** [comment]
> Will provide a PR soon. 

@krull, that would be awesome.

You're right, host should not have access to containers, and what you see are mostly leftovers from development :) Namely, the script in question is used in dev environment (e.g. you run Kazoo on your laptop, and in this scenario adding entries to hosts seems feasible). But current production design supposes the setup you've described: nginx/haproxy in front of kazoo, rtp routing/natting to fs instances, and ip routing/natting to kamailio instance. I'm actually working to automate this, e.g. given a host with docker one should be able to install working docker-based Kazoo instance quickly.

Other thing is how to install two (and more) instances of docker-based Kazoo and make them work together, but this is a bit different story.

**Comment by krull** [comment]
> Other thing is how to install two (and more) instances of docker-based Kazoo and make them work together, but this is a bit different story.

Challenge accepted :)

My couchdb instance here is now persistent, but I'm having an issue with a failing kazoo.kazoo container. Do you have anywhere in the image hardcoded the network 'kazoo'?

I will have a peek in the image to see why it is failing... and I'll git push on my fork for you to see once I'm satisfied on my end.

krull

**Comment by jamhed** [comment]
Well, the idea is that you have an isolated docker network segment with various Kazoo components attached, and they're visible to each other by their names in form component.network (this way you can have more than one Kazoo instances on the same host), therefore the answer is yes, network name is used inside containers, but all such uses are actually configured during runtime. At least they should.
