### ISSUE TITLE
couchdb 1.6 uses port 15984, but couchdb 2.0 uses 5984

### ISSUE THREAD

**Issue by krull** [jamhed/kazoo-docker#9]
@jamhed The image builds of `2600hz/couchdb` of Feb 17 uses [couchdb 1.6](https://github.com/2600hz/docker/blob/master/export/all.sh#L4) which broke the run.sh process as kazoo.kazoo config was pointing to couchdb2's port 5984, resulting in the following error when running ./run.sh:

```
(kazoo@kazoo.kazoo)1> 11:37:24.938 info kz_dataconnection.161 trying to connect kazoo_couch
(kazoo@kazoo.kazoo)1> 11:37:24.940 warning kz_couch_util.338 connection to http://couchdb.kazoo:5984 failed: econnrefused
(kazoo@kazoo.kazoo)1> 11:37:24.940 info kz_dataconnection.171 failed to connect with kazoo_couch : {error,econnrefused} : #{admin_port => 5986,compact_automatically => true,cookie => change_me,driver => kazoo_couch,ip => "couchdb.kazoo",port => 5984,tag => local}
```

I built couchdb2 locally and it is working fine. FYI.

**Comment by jamhed** [comment]
@krull, should work now as I've updated everything.

**Comment by krull** [comment]
@jamhed, thanks. Can confirm that everything works as it should now. Closing thread.
